language: php

php:
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - mysql -e 'create database laravel;'
  - php artisan --env=testing migrate --package="cartalyst/sentry"
  - php artisan --env=testing migrate
  - php artisan --env=testing db:seed
  - php artisan --env=testing createusers:create --minimum="100"
  - php artisan --env=testing createtutorials:create --minimum="1000"
  - php artisan --env=testing createassessments:create --minimum="1000"
